In [1]:
import pandas as pd

In [2]:
nasdaq = pd.read_csv('/Users/ngocnguyen/Downloads/HistoricalData_1739420282858.csv')

In [3]:
nasdaq.head()

         Date  Close/Last     Open     High      Low
0  02/11/2025     6068.50  6049.32  6076.28  6042.34
1  02/10/2025     6066.44  6046.40  6073.38  6044.84
2  02/07/2025     6025.99  6083.13  6101.28  6019.96
3  02/06/2025     6083.57  6072.22  6084.03  6046.83
4  02/05/2025     6061.48  6020.45  6062.86  6007.06

In [4]:
# Convert 'Date' column to datetime format
nasdaq['Date'] = pd.to_datetime(nasdaq['Date'], errors='coerce')

# Filter for records in the year 2018
nasdaq = nasdaq[(nasdaq['Date'] >= '2018-01-01') & (nasdaq['Date'] <= '2018-12-31')]

# Ensure 'Open' and 'Close/Last' are numeric
nasdaq['Open'] = pd.to_numeric(nasdaq['Open'], errors='coerce')
nasdaq['Close/Last'] = pd.to_numeric(nasdaq['Close/Last'], errors='coerce')

# Calculate avg_value
nasdaq['avg_value'] = (nasdaq['Close/Last'] - nasdaq['Open']) / nasdaq['Open']

In [5]:
nasdaq.head(10)

           Date  Close/Last     Open     High      Low  avg_value
1537 2018-12-31     2506.85  2498.94  2509.24  2482.82   0.003165
1538 2018-12-28     2485.74  2498.77  2520.27  2472.89  -0.005215
1539 2018-12-27     2488.83  2442.50  2489.10  2397.94   0.018968
1540 2018-12-26     2467.70  2363.12  2467.76  2346.58   0.044255
1541 2018-12-24     2351.10  2400.56  2410.34  2351.10  -0.020604
1542 2018-12-21     2416.62  2465.38  2504.41  2408.55  -0.019778
1543 2018-12-20     2467.42  2496.77  2509.63  2441.18  -0.011755
1544 2018-12-19     2506.96  2547.05  2585.29  2488.96  -0.015740
1545 2018-12-18     2546.16  2559.90  2573.99  2528.71  -0.005367
1546 2018-12-17     2545.94  2590.75  2601.13  2530.54  -0.017296

In [6]:
nasdaq["Index Price"] = nasdaq["Close/Last"] - nasdaq["Open"]
nasdaq.head()

           Date  Close/Last     Open     High      Low  avg_value  Index Price
1537 2018-12-31     2506.85  2498.94  2509.24  2482.82   0.003165         7.91
1538 2018-12-28     2485.74  2498.77  2520.27  2472.89  -0.005215       -13.03
1539 2018-12-27     2488.83  2442.50  2489.10  2397.94   0.018968        46.33
1540 2018-12-26     2467.70  2363.12  2467.76  2346.58   0.044255       104.58
1541 2018-12-24     2351.10  2400.56  2410.34  2351.10  -0.020604       -49.46

In [7]:
# Drop unnecessary columns
nasdaq = nasdaq.drop(columns=["Open", "High", "Low", "avg_value"])
nasdaq.head()

           Date  Close/Last  Index Price
1537 2018-12-31     2506.85         7.91
1538 2018-12-28     2485.74       -13.03
1539 2018-12-27     2488.83        46.33
1540 2018-12-26     2467.70       104.58
1541 2018-12-24     2351.10       -49.46

In [8]:
nasdaq.to_csv("nasdaq_index.csv", index=False)